# Generated by Django 5.1 on 2024-08-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_review_reviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='owner_comment',
            field=models.TextField(null=True),
        ),
    ]
