# Generated by Django 5.1 on 2024-08-24 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='ReviewModel',
        ),
    ]
