# Generated by Django 5.1 on 2024-08-17 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0003_country_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_store.author'),
        ),
    ]
